BEGIN;

-- CONFIGURACION DE SEGURIDAD (RLS)
ALTER TABLE public.equipos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir lectura publica de equipos" ON public.equipos;
CREATE POLICY "Permitir lectura publica de equipos" ON public.equipos FOR SELECT USING (true);

ALTER TABLE public.partidos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir lectura publica de partidos" ON public.partidos;
CREATE POLICY "Permitir lectura publica de partidos" ON public.partidos FOR SELECT USING (true);

-- INSERTAR EQUIPOS
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('México', 'MEX', 'mx', 'A') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Sudáfrica', 'RSA', 'za', 'A') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('República de Corea', 'KOR', 'kr', 'A') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Chequia', 'CZE', 'cz', 'A') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Canadá', 'CAN', 'ca', 'B') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Bosnia y Herzegovina', 'BIH', 'ba', 'B') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Catar', 'QAT', 'qa', 'B') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Suiza', 'SUI', 'ch', 'B') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Brasil', 'BRA', 'br', 'C') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Marruecos', 'MAR', 'ma', 'C') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Haití', 'HAI', 'ht', 'C') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Escocia', 'SCO', 'gb-sct', 'C') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('EE. UU.', 'USA', 'us', 'D') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Paraguay', 'PAR', 'py', 'D') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Australia', 'AUS', 'au', 'D') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Turquía', 'TUR', 'tr', 'D') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Alemania', 'GER', 'de', 'E') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Curazao', 'CUW', 'cw', 'E') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Costa de Marfil', 'CIV', 'ci', 'E') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Ecuador', 'ECU', 'ec', 'E') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Países Bajos', 'NED', 'nl', 'F') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Japón', 'JPN', 'jp', 'F') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Suecia', 'SWE', 'se', 'F') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Túnez', 'TUN', 'tn', 'F') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Bélgica', 'BEL', 'be', 'G') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Egipto', 'EGY', 'eg', 'G') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('RI de Irán', 'IRN', 'ir', 'G') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Nueva Zelanda', 'NZL', 'nz', 'G') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('España', 'ESP', 'es', 'H') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Islas de Cabo Verde', 'CPV', 'cv', 'H') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Arabia Saudí', 'KSA', 'sa', 'H') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Uruguay', 'URU', 'uy', 'H') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Francia', 'FRA', 'fr', 'I') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Senegal', 'SEN', 'sn', 'I') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Irak', 'IRQ', 'iq', 'I') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Noruega', 'NOR', 'no', 'I') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Argentina', 'ARG', 'ar', 'J') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Argelia', 'ALG', 'dz', 'J') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Austria', 'AUT', 'at', 'J') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Jordania', 'JOR', 'jo', 'J') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Portugal', 'POR', 'pt', 'K') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('RD Congo', 'COD', 'cd', 'K') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Uzbekistán', 'UZB', 'uz', 'K') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Colombia', 'COL', 'co', 'K') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Inglaterra', 'ENG', 'gb-eng', 'L') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Croacia', 'CRO', 'hr', 'L') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Ghana', 'GHA', 'gh', 'L') ON CONFLICT (codigo_iso) DO NOTHING;
INSERT INTO public.equipos (nombre, siglas, codigo_iso, grupo) VALUES ('Panamá', 'PAN', 'pa', 'L') ON CONFLICT (codigo_iso) DO NOTHING;

-- INSERTAR PARTIDOS
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('mx', 'za', '2026-06-11T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('kr', 'cz', '2026-06-11T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('cz', 'za', '2026-06-18T12:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('mx', 'kr', '2026-06-18T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('cz', 'mx', '2026-06-24T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('za', 'kr', '2026-06-24T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ca', 'ba', '2026-06-12T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('qa', 'ch', '2026-06-13T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ch', 'ba', '2026-06-18T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ca', 'qa', '2026-06-18T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ch', 'ca', '2026-06-24T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ba', 'qa', '2026-06-24T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('br', 'ma', '2026-06-13T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ht', 'gb-sct', '2026-06-13T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('gb-sct', 'ma', '2026-06-19T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('br', 'ht', '2026-06-19T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('br', 'gb-sct', '2026-06-24T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ma', 'ht', '2026-06-24T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('us', 'py', '2026-06-12T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('au', 'tr', '2026-06-13T00:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('us', 'au', '2026-06-19T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('tr', 'py', '2026-06-19T00:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('tr', 'us', '2026-06-25T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('py', 'au', '2026-06-25T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('de', 'cw', '2026-06-14T13:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ci', 'ec', '2026-06-14T19:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('de', 'ci', '2026-06-20T16:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ec', 'cw', '2026-06-20T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('cw', 'ci', '2026-06-25T16:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ec', 'de', '2026-06-25T16:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('nl', 'jp', '2026-06-14T16:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('se', 'tn', '2026-06-14T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('nl', 'se', '2026-06-20T13:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('tn', 'jp', '2026-06-20T00:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('jp', 'se', '2026-06-25T19:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('tn', 'nl', '2026-06-25T19:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('be', 'eg', '2026-06-15T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ir', 'nz', '2026-06-15T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('be', 'ir', '2026-06-21T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('nz', 'eg', '2026-06-21T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('eg', 'ir', '2026-06-26T23:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('nz', 'be', '2026-06-26T23:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('es', 'cv', '2026-06-15T12:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('sa', 'uy', '2026-06-15T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('es', 'sa', '2026-06-21T12:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('uy', 'cv', '2026-06-21T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('cv', 'sa', '2026-06-26T20:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('uy', 'es', '2026-06-26T20:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('fr', 'sn', '2026-06-16T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('iq', 'no', '2026-06-16T18:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('fr', 'iq', '2026-06-22T17:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('no', 'sn', '2026-06-22T20:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('no', 'fr', '2026-06-26T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('sn', 'iq', '2026-06-26T15:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ar', 'dz', '2026-06-16T21:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('at', 'jo', '2026-06-16T00:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('ar', 'at', '2026-06-22T13:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('jo', 'dz', '2026-06-22T23:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('dz', 'at', '2026-06-27T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('jo', 'ar', '2026-06-27T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('pt', 'cd', '2026-06-17T13:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('uz', 'co', '2026-06-17T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('pt', 'uz', '2026-06-23T13:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('co', 'cd', '2026-06-23T22:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('co', 'pt', '2026-06-27T19:30:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('cd', 'uz', '2026-06-27T19:30:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('gb-eng', 'hr', '2026-06-17T16:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('gh', 'pa', '2026-06-17T19:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('gb-eng', 'gh', '2026-06-23T16:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('pa', 'hr', '2026-06-23T19:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('pa', 'gb-eng', '2026-06-27T17:00:00-06:00', 'Fase de Grupos', 'Pendiente');
INSERT INTO public.partidos (equipo_local_id, equipo_visitante_id, fecha_hora, fase, estado) VALUES ('hr', 'gh', '2026-06-27T17:00:00-06:00', 'Fase de Grupos', 'Pendiente');

COMMIT;
